# Site settings
title: "Sparkle: open source software update framework for macOS"
url: "http://sparkle-project.org"
github_username: sparkle-project

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
