name: "Update Carthage Package"

on:
  workflow_dispatch

concurrency: 
  group: update-repo-${{ github.ref }}
  cancel-in-progress: false

jobs:
  api-documentation:
    name: "Update Carthage Package"
    runs-on: macos-11

    steps:
      - name: "Checkout Sparkle Sources"
        uses: actions/checkout@v2
        with:
          repository: 'sparkle-project/Sparkle'
          token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0
          path: 'sparkle-source'

      - name: "Checkout Website Sources"
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          path: 'sparkle-website'

      - name: "Copy Carthage json"
        run: |
            cd "$GITHUB_WORKSPACE/sparkle-website"
            cp "$GITHUB_WORKSPACE/sparkle-source/Carthage-dev.json" "Carthage/Sparkle.json"

      - name: "Commit and Push Changes"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
        run: |
            cd "$GITHUB_WORKSPACE/sparkle-website"
            git config user.name Sparkle-Bot
            git config user.email sparkle.project.bot@gmail.com
            git add "Carthage/Sparkle.json"
            git commit -m "Update Carthage spec"
            git push
